// Auto-generated code. Do not edit.
namespace myTiles {
    //% fixedInstance jres blockIdentity=images._tile
    export const transparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const tile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile5 = image.ofBuffer(hex``);
}
// Auto-generated code. Do not edit.
