// Auto-generated code. Do not edit.
namespace myTiles {
    //% fixedInstance jres blockIdentity=images._tile
    export const transparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zgltile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zyxtile30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const zhrtile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const xcxtile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const dztile5 = image.ofBuffer(hex``);
}
// Auto-generated code. Do not edit.
